### ISSUE TITLE
RxScala Bootstrap

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxScala#1]
RxScala has been extracted from RxJava prior to 1.0 as per https://github.com/ReactiveX/RxJava/issues/589

I have done this with a simply copy/paste/commit for now. Commit history remains in the 0.20.x branch of RxJava: https://github.com/ReactiveX/RxJava/tree/0.20.x

If anyone wishes to replace the code in this project with files that retain commit history, go ahead and make the changes.

Over the coming weeks the build and release process will be updated. 

This project does not need to release immediately as 1.0. It can continue with 0.x releases until it makes sense to hit 1.0. Its lifecycle is now decoupled from RxJava.

**Comment by samuelgruetter** [comment]
I think it's important to keep the history. I extracted the Scala files using `git filter-branch` into this repo:

https://github.com/samuelgruetter/RxScala

I also made sure that all tags are kept, so that one can easily browse the source of an older release. This increases the size of the `.git` folder, because the Java files referenced by the tags are still kept, but I think keeping the tags is worth some disk space ;-)

I won't make a PR, because the two repos are not compatible. @benjchristensen I'd suggest that you force-push `samuelgruetter/RxScala` to `ReactiveX/RxScala` (making sure the tags are kept), if you're OK with that.

**Comment by zsxwing** [comment]
@samuelgruetter you forgot `rxjava-scalaz`. Is there any magic command to `Splitting two subfolders out into a new repository`? If not, just manually adding `rxjava-scalaz` looks fine since there are only several commits.

**Comment by benjchristensen** [comment]
Thank you for figuring this out. I saw there was probably a way to do it when Googling but was too tired last night to try.

I'll force push so the starting point is correct and then update the builds ... all the build stuff will be changing in the next week or two as well.

**Comment by benjchristensen** [comment]
Are you okay with the scalaz module being part of RxScala?

**Comment by headinthebox** [comment]
I strongly vote to keep the Scalaz parts out on their own, and make that independent add-on using extension methods.

**Comment by samuelgruetter** [comment]
> Are you okay with the scalaz module being part of RxScala?

The important point is that we can ship an RxScala JAR which does not depend on scalaz. Whether or not their source is in the same github repo is a different question, and I'm not (yet) sure what's better.

**Comment by samuelgruetter** [comment]
Another point is that if we have the scalaz parts in a separate repo, it's easier to have a separate versioning there (if that's desired).
/cc @everpeace

**Comment by jbripley** [comment]
I'd also prefer Scalaz to be a separate repo.

**Comment by everpeace** [comment]
Hello guys.  OK. I agree that I will create separate repo of `rxjava-scalaz` because of easier independent versioning.  I'm ok to proceed `RxScala` bootstrap without scalaz part.

**Comment by benjchristensen** [comment]
The history of RxScala is restored. The structure will change though, and all the build setup will change in the coming days.

**Comment by benjchristensen** [comment]
@everpeace How do you want to do this?

**Comment by everpeace** [comment]
@benjchristensen Thank you for your kindness.   As @samuelgruetter pointed out, `RxScala` can ship its jar with no dependency to scalaz.  So, I think there is not so big issue if `rxjava-sclaz` will be in `RxScala` repo.  Besides, I think it's better that `RxScala` ships some functional type class instances for functional programmers.

However, unfortunately, I recognize some contributors want to make it independent module.  The reason might be my recent inactive contribution to the component.  Respecting active contributors intention, I can choose that I will create my own repo for `rxjava-scalaz`.

**Comment by headinthebox** [comment]
> Respecting active contributors intention, I can choose that I will create my own repo for rxjava-scalaz.

That might be the optimal solution.

**Comment by everpeace** [comment]
@headinthebox Yes, I think so too.  That's why I agreed firstly. I will do that after 1.0 release.

I would be very happy if `rx-java-scalaz` would be on `RxScala`'s README.  Is that possible?

**Comment by benjchristensen** [comment]
There is a list on the Wiki where it can be referenced: https://github.com/ReactiveX/RxJava/wiki#rxjava-libraries. Once RxScala gets its docs in place it can be added there as well.

Once www.reactivex.io is fully alive we can have a list of 3rd party Rx libraries.

**Comment by everpeace** [comment]
@benjchristensen Oh, that sounds nice. Thanks!

**Comment by mighdoll** [comment]
noting here that we should cross build a 2.11 version (as well as labeling the 2.10 version appropriately.)

**Comment by zsxwing** [comment]
@benjchristensen, @quidryan  could you help take a look at https://github.com/nebula-plugins/gradle-rxjava-project-plugin/issues/1 ?

**Comment by jmhofer** [comment]
Cross building is in now thanks to sbt.

**Comment by zsxwing** [comment]
Cool, Thanks @jmhofer
