### ISSUE TITLE
ScalaDoc for Observable.subscribe() seems to be incorrect.

### ISSUE THREAD

**Issue by jhegedus42** [ReactiveX/RxScala#121]
http://reactivex.io/rxscala/scaladoc/index.html#rx.lang.scala.Observable@subscribe():rx.lang.scala.Subscription

subscribe() takes no parameters, so the following documentation seems to be incorrect "Call this method to subscribe an rx.lang.scala.Observer for receiving items and notifications from the Observable."

**Comment by zsxwing** [comment]
Thank you for reporting it.
