### ISSUE TITLE
v0.24

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxScala#147]
Is 0.24 ready to release? We need the new `takeUntil` overload.

cc @bpitman

**Comment by zsxwing** [comment]
I added it in pr #146
We're looking for a best approach to add the experimental APIs.

**Comment by benjchristensen** [comment]
No annotations or other such mechanisms for marking APIs in scala?

If not that, then just Scaladocs?

**Comment by zsxwing** [comment]
The experimental APIs(methods) of RxJava Observable will be extension methods in RxScala, and needs to be imported explicitly. E.g.,

``` Scala
    import rx.lang.scala.ExperimentalAPIs._

    Observable.just(1, 2, 3, 4, 5, 6, 7).
      doOnNext(v => println(s"onNext: $v")).
      takeUntil((x: Int) => x == 3). 
      foreach(println)
```

However, for the experimental classes, such as `AbstractOnSubscribe`, I would like to use @Beta/@Experimental annotations. What do you think?

**Comment by benjchristensen** [comment]
I am a novice with Scala so my opinion isn't worth anything here. Whatever you and the others decide.

**Comment by zsxwing** [comment]
Just wrote a release note for 0.24.0 #148

**Comment by zsxwing** [comment]
@benjchristensen  I just released 0.24.0. However, Bintray cannot sync the files to Sonatype automatically. Could you help sync them?

I found an API of Bintray here: https://bintray.com/docs/api/#_sync_version_artifacts_to_maven_central
It requires the username and password of Sonatype.

```
{
  "username": "userToken", // Sonatype OSS user token
  "password": "passwordToken", // Sonatype OSS user password
  "close": "1" // Optional
}
```

The `bintray-sbt` plugin uses it to sync files. Could you put them into .travis.yml as secure environments? I will try it to make the `bintray-sbt` plugin do the synchronization.

**Comment by benjchristensen** [comment]
Bintray should do all of that automatically. It saves it. For example, on the Gradle builds we don't need those credentials.

**Comment by benjchristensen** [comment]
Manually synced.

**Comment by zsxwing** [comment]
Thanks @benjchristensen 

But I think Bintray doesn't do it automatically. `nebula-bintray-plugin` syncs the files. See https://github.com/nebula-plugins/nebula-bintray-plugin/blob/15af24355cc4816c25034b4cf234071fa4497346/src/main/groovy/nebula/plugin/bintray/NebulaBintraySyncPublishingPlugin.groovy It calls the API I mentioned previously.

There is a log in this plugin: `logger.info("Package Sync: $uploadUri")`. Could you verify it in the CloudBees log? I think RxJava is still published by CloudBees, right?

**Comment by benjchristensen** [comment]
RxJava is published via Travis and no longer uses CloudBees. I noticed I have to manually sync bintray on that as well so we need to figure out what is missing. 

@quidryan What is missing in our publishing process to trigger the Bintray->MavenCentral sync?

**Comment by quidryan** [comment]
The sonatype credentials weren't being provided to Gradle in the shell script. @rspieldenner is working on adding them.

**Comment by zsxwing** [comment]
@benjchristensen could you add `sonatypeUsername` and `sonatypePassword` for RxScala?

**Comment by rspieldenner** [comment]
I'll do that today

**Comment by zsxwing** [comment]
The names of the environment variables should be `SONA_USER` and `SONA_PASS`.

**Comment by zsxwing** [comment]
Closing. I updated the publish script. Will test it when publishing the next release.
