### ISSUE TITLE
Broken links to examples on site

### ISSUE THREAD

**Issue by sslavic** [ReactiveX/RxScala#153]
On http://reactivex.io/rxscala/ page, the first two links in sentence "Get started by looking at RxScalaDemo.scala, the RxScala examples, or the Scaladoc." are broken.

RxScalaDemo.scala link should probably use https://github.com/ReactiveX/RxScala/blob/0.x/examples/src/test/scala/rx/lang/scala/examples/RxScalaDemo.scala URL.

**Comment by samuelgruetter** [comment]
Thanks for pointing it out! Would you mind making a pull request to the `develop` branch of the [repo of the website](https://github.com/ReactiveX/reactivex.github.io)?

**Comment by sslavic** [comment]
Created https://github.com/ReactiveX/reactivex.github.io/pull/106

**Comment by samuelgruetter** [comment]
thanks :-)
