### ISSUE TITLE
Sync to maven central does not work

### ISSUE THREAD

**Issue by zsxwing** [ReactiveX/RxScala#154]
looks the user account you set does not have permission. Could you take a look?

```
User 'jryan_netflix' missing 'stage' permission for staging profile: 6e7dce69b90173
```

Log: https://travis-ci.org/ReactiveX/RxScala/builds/56530568

/cc @rspieldenner

**Comment by zsxwing** [comment]
ping  @rspieldenner @quidryan @benjchristensen

**Comment by rspieldenner** [comment]
Used the wrong account: current problem which 4 of the properties are ours?

**Comment by rspieldenner** [comment]
see #155

**Comment by zsxwing** [comment]
Now it works. Thanks a lot, @rspieldenner
