### ISSUE TITLE
Scala.js support

### ISSUE THREAD

**Issue by myhau** [ReactiveX/RxScala#161]
Will there ever be scala.js support like in [monifu](https://github.com/monifu/monifu) ?

**Comment by headinthebox** [comment]
I think the layering on top of RxJava makes that road impossible.

**Comment by samuelgruetter** [comment]
An interesting thing, though, would be to copy the whole RxScala project into a new folder, and then replace all calls to RxJava by calls to [RxJS](https://github.com/Reactive-Extensions/RxJS), and to compile it with Scala.js. Then we could cross-build Scala code using Observables for the JVM and for JavaScript.

**Comment by headinthebox** [comment]
That's definitively possible, but the API differences are nontrivial.

**Comment by samuelgruetter** [comment]
So what are the biggest API differences between RxJava and RxJS? As far as backpressure is concerned, it looks like RxJS will move closer to what RxJava does (see [Roadmap for RxJS 2.4](https://github.com/Reactive-Extensions/RxJS/issues/335) and [Future work on backpressure](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/gettingstarted/backpressure.md#future-work)).

**Comment by LukaJCB** [comment]
Wouldn't it be possible to convert the RxJava code to Scala code?

**Comment by samuelgruetter** [comment]
Sounds a bit crazy, but maybe you could do so using a Java to Scala converter, such as http://javatoscala.com/ ...

**Comment by LukaJCB** [comment]
I was thinking the same thing. Probably not going to work 100%, but might be better than converting everything to RxJS.

**Comment by zsxwing** [comment]
> Sounds a bit crazy, but maybe you could do so using a Java to Scala converter, such as http://javatoscala.com/ ...

I think most of Schedulers won't work since Scala.js/JavaScript doesn't support threads.

**Comment by LukaJCB** [comment]
Ah yes, in that case, might be easier to just write a facade to RxJs

**Comment by LukaJCB** [comment]
If anyone's interested, I've started a wraper some time ago: https://github.com/lukajcb/rxscala-js

**Comment by samuelgruetter** [comment]
Interesting... Did you also write some sample RxScala apps which cross-compile to both JVM and JS?

**Comment by zsxwing** [comment]
Cool 👍 It would be great to see some samples :)

**Comment by LukaJCB** [comment]
Working on it as we speak, there's still tons of work to do, but I'm trying to keep it as close to the Scala Api as possible!

**Comment by LukaJCB** [comment]
I'm finally at a point where I'm confident with showing it, be free to check it out! :)
https://github.com/lukajcb/rxscala-js
The API now mostly works just as the RxScala Api.

**Comment by headinthebox** [comment]
Nice!

**Comment by samuelgruetter** [comment]
Nice :smiley: 
Are you already using it in a project of yours?

**Comment by LukaJCB** [comment]
Not yet, but once it's fully polished I'd like to build a minimal Web framework on top of it and virtual dom. 😃

**Comment by LukaJCB** [comment]
I did a (very) quick port of Sergi Mansilla's Spaceship Reactive, which can be found here: https://github.com/LukaJCB/RxScalaJsSamples. And the working version can be found at https://lukajcb.github.io/RxScalaJsSamples/

**Comment by dhoepelman** [comment]
Due to project EOL status, Scala.JS will not be supported
