### ISSUE TITLE
RxScala Build

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxScala#17]
We need to get the build and release process for RxScala functioning.

One requirement of RxScala that differs from other projects is it wants the ability to publish multiple artifacts based on different Scala versions. An issue for the Nebula plugin is at https://github.com/nebula-plugins/gradle-rxjava-project-plugin/issues/1

This is holding up progressing on RxScala as no new releases can be made beyond 0.20.x right now.

/cc @quidryan

**Comment by benjchristensen** [comment]
Our goal is to keep as close as possible to RxJava and leverage the work on the Nebula RxJava plugin so as to benefit from the shared effort, particularly around releases to Maven Central. 

The RxScala community can migrate this to SBT if wanted, but then the RxJava team and ecosystem will not be able to help RxScala with any build and release items.

**Comment by jmhofer** [comment]
I'm currently trying to move this to an sbt build because this should be quite easy. 

However, it doesn't even compile. Which version of RxJava is this currently compatible with? The gradle build says "io.reactivex:rxjava:1.0.+", but my attempt with 1.0.0-rc.3 failed.

**Comment by benjchristensen** [comment]
So you're going to also take on the task of getting the binary release to Maven Central working?

**Comment by jmhofer** [comment]
I intend to do so. Does ReactiveX have some specific repository to publish to that syncs with Maven Central?

Btw, I got it to compile now. There were just a lot of deprecated methods still in that I deleted.

**Comment by benjchristensen** [comment]
Yes we do. It is Bintray: https://bintray.com/reactivex/RxJava/RxScala/view

You'll need to use Travis and setup an "after_success" script to run and do the release process.

See here for me playing with it: https://github.com/ReactiveX/BuildInfrastructure/blob/master/.travis.yml

I'll add the secure variables to the .travis.yml file. 

Note here how the `publishViaTravis.sh` file only executes the logic if it is a tag being pushed: https://github.com/ReactiveX/BuildInfrastructure/blob/master/gradle/publishViaTravis.sh#L6

This is the mechanism for a committer triggering a release by tagging.

**Comment by jmhofer** [comment]
Awesome. I'll take a look.

**Comment by benjchristensen** [comment]
I just added `bintrayUser` and `bintrayKey` as secure env variables to https://github.com/ReactiveX/RxScala/blob/0.x/.travis.yml

**Comment by jmhofer** [comment]
Thanks. Next, I have to find a way to turn these environment variables into publishing credentials for sbt-bintray. After that, it might work...
