### ISSUE TITLE
toJavaObservable

### ISSUE THREAD

**Issue by richardhundt** [ReactiveX/RxScala#177]
Hi, awesome project!

I've got a puzzler though. I'm expecting the following to work:

``` Scala
scala> import rx.lang.scala._
import rx.lang.scala._

scala> import rx.lang.scala.JavaConversions._
import rx.lang.scala.JavaConversions._

scala> :paste
// Entering paste mode (ctrl-D to finish)

val a = Observable.just(1,2,3)
val b = a.toJavaObservable

// Exiting paste mode, now interpreting.

<console>:14: error: value toJavaObservable is not a member of rx.lang.scala.Observable[Int]
       val b = a.toJavaObservable
```

Whereas `JavaConversions.toJavaObservable(a)` does work. Not sure why the implicits aren't resolving. Any ideas?

**Comment by zsxwing** [comment]
When you call `a.toJavaObservable`, the Scala compiler will try to find an implicit conversion that can convert `a` to an instance that has a method called `toJavaObservable`. Obviously, it cannot find.

The implicit `toJavaObservable` works when you put a `rx.lang.scala.Observable` to a place that requires `rx.Observable`. E.g.,

```
rx.lang.scala.Observable.just("String").ofType(classOf[CharSequence])
```

`ofType` is not a `rx.lang.scala.Observable` method. But the Scala compiler finds `rx.Observable` has a `ofType` method and also the implicit `toJavaObservable` that can convert  `rx.lang.scala.Observable` to `rx.Observable`. So the compiler will expand the statement to 

```
toJavaObservable(rx.lang.scala.Observable.just("String")).ofType(classOf[CharSequence])
```

**Comment by richardhundt** [comment]
Ah right, not sure why I thought you had an implicit classes instead of implicit defs. Thanks!
