### ISSUE TITLE
`delay` on `interval` will throw `NoSuchElementException`?

### ISSUE THREAD

**Issue by freewind** [ReactiveX/RxScala#180]
Have posted it here:

http://stackoverflow.com/questions/33696615/delay-on-interval-will-throw-nosuchelementexception

**Comment by zsxwing** [comment]
Thanks for reporting it. There is a RxJava bug in `zipWith(Iterable)`. I have sent a PR to fix it. For now, you can use `Observable.interval(Duration("100 millis")).zip(Observable.from(Seq(1, 2, 3))).map(_._2).delay(Duration("2 s"))` as a workaround.
