### ISSUE TITLE
Experimental Class: Single/SingleSubscriber

### ISSUE THREAD

**Issue by zsxwing** [ReactiveX/RxScala#186]
See:

https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/Single.java
https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/SingleSubscriber.java

**Comment by samuelgruetter** [comment]
Looks interesting... What's the status of these in RxJava? Did they prove to be useful and will remain there?

**Comment by zsxwing** [comment]
I think some Android developers like this one. Most of their cases only need this special Observable, e.g., request a request from network and render it in UI. In addition, see https://github.com/ReactiveX/RxJava/issues/1594#issuecomment-101300655 for the discussion in RxJava.

**Comment by hyleung** [comment]
@samuelgruetter last I checked in RxJava, `rx.Single` is still `@Beta`. That being said, I think it has had a fair bit of traction - my team at work uses it in the code base (so hopefully it doesn't go away!). One thing that takes a bit getting used to is that `Single`s can only emit a value or error, there is no "empty".

**Comment by dhoepelman** [comment]
Due to project EOL status, `Single` will not be ported from RxJava
