### ISSUE TITLE
Experimental Class: Completable

### ISSUE THREAD

**Issue by zsxwing** [ReactiveX/RxScala#187]
See:

https://github.com/ReactiveX/RxJava/blob/1.x/src/main/java/rx/Completable.java

**Comment by samuelgruetter** [comment]
Can't we achieve almost the same with `Observable[Nothing]` and `ignoreElements()`? Or asked differently: Do you think the gain in conciseness is worth the increase in API surface?

**Comment by zsxwing** [comment]
Yeah, I'm not sure how helpful this one. Let's just keep it open and see if people are interested in it.

**Comment by dhoepelman** [comment]
Due to project EOL status, `Completable` will not be ported from RxScala
