### ISSUE TITLE
RxJava 1.1.9 : TestSubscriber.assertValuesAndClear

### ISSUE THREAD

**Issue by imcharsi** [ReactiveX/RxScala#202]
Hi.

I think that it would be better if RxScala supports this [assertValuesAndClear](https://github.com/ReactiveX/RxJava/pull/4322) feature.

See [here](https://github.com/ReactiveX/RxJava/issues/4284).

Thanks for reading.

**Comment by samuelgruetter** [comment]
Hi @imcharsi! Yes, this should definitely be added. This is an opensource project, would you have time to prepare a pull request for it?

**Comment by imcharsi** [comment]
Hi.
I'll try it.
Thanks for reading.

**Comment by zsxwing** [comment]
Added in #204
