### ISSUE TITLE
@deprecated annotation not in ScalaDoc

### ISSUE THREAD

**Issue by samuelgruetter** [ReactiveX/RxScala#205]
(sorry in advance for nitpicking ;-) )

In the source of [Observable.scala](https://github.com/ReactiveX/RxScala/blob/0.x/src/main/scala/rx/lang/scala/Observable.scala#L4876), there's an `@deprecated` annotation for `def create[T](f: Observer[T] => Subscription): Observable[T]`.

However, in the [ScalaDoc](http://reactivex.io/rxscala/scaladoc/index.html#rx.lang.scala.Observable$), I can't see any deprecation notice.

Why is this? Is it a problem with ScalaDoc? Or is the ScalaDoc just not up to date?

**Comment by zsxwing** [comment]
It's just out of date. I will send a PR to update.

Maybe we should put the scaladoc to the `gh-pages` branch so that we can add scripts to update the docs when doing a release.

**Comment by samuelgruetter** [comment]
yes, a script which ensures that the docs are always those of the latest release would be great :+1:

**Comment by zsxwing** [comment]
Closing this one since the doc has been updated.
