### ISSUE TITLE
Remove create[T](f: Observer[T] => Subscription)

### ISSUE THREAD

**Issue by samuelgruetter** [ReactiveX/RxScala#206]
Let's remove 

```
def create[T](f: Observer[T] => Subscription): Observable[T]
```

once the deprecation process/release schedule allows it.
Reason: It was removed in RxJava, and people get confused by its presence, eg:
- http://stackoverflow.com/questions/39212913/subscription-without-any-parameters
- https://github.com/ReactiveX/RxScala/issues/195

**Comment by samuelgruetter** [comment]
Note: We already agreed to deprecate it in https://github.com/ReactiveX/RxScala/pull/196

**Comment by zsxwing** [comment]
👍 I saw no course for RxScala now: https://www.coursera.org/specializations/scala

**Comment by dhoepelman** [comment]
Due to project EOL status, this will not be removed
