### ISSUE TITLE
Missing 0.26.4 artefacts for 2.11

### ISSUE THREAD

**Issue by lloydmeta** [ReactiveX/RxScala#217]
According to [this](http://search.maven.org/#search%7Cga%7C1%7C%22rxscala%22%20AND%20g%3A%22io.reactivex%22), 0.26.4 isn't up for 2.11.

**Comment by zsxwing** [comment]
Thanks for reporting it. Looks like there was some error when syncing from bintray to maven central. I just pushed a commit to resync. Let's see if it will be fixed.

**Comment by zsxwing** [comment]
Forgot to mention one thing: it's in https://oss.sonatype.org/content/repositories/releases/io/reactivex/rxscala_2.11/0.26.4/ now. So should be available on maven central.

I guess the issue is bintray maven sync doesn't support multiple requests running at the same time.

**Comment by lloydmeta** [comment]
Thanks for fixing the problem ! It's available now so I'll close this issue.
