### ISSUE TITLE
replace `=> Unit` by `() => Unit`

### ISSUE THREAD

**Issue by samuelgruetter** [ReactiveX/RxScala#225]
I suggest that we replace all `=> Unit` arguments by `() => Unit`.
See https://github.com/ReactiveX/RxScala/issues/175 for more discussion/explanation.
This would affect the following methods (provided that I didn't miss any :wink:):
* doAfterTerminate
* doOnTerminate
* doOnCompleted
* doOnSubscribe
* doOnUnsubscribe
* onBackpressureBuffer

**Comment by zsxwing** [comment]
Sounds good to me

**Comment by dhoepelman** [comment]
Due to project EOL status, this change will not be made
