### ISSUE TITLE
Can't find Observable.compose(), any alternatives?

### ISSUE THREAD

**Issue by grant-guo** [ReactiveX/RxScala#230]

**Comment by samuelgruetter** [comment]
There's a [guide](http://reactivex.io/rxscala/comparison.html) which should answer all questions of this kind.
`compose` was intentionally left out because it is considered non-Scala-idiomatic.
As the guide suggests, I'd use extension methods.

**Comment by grant-guo** [comment]
@samuelgruetter Thanks!
you mean I have to use implicit class to wrap a rxjava Observable inside?

**Comment by samuelgruetter** [comment]
Yes, but I'd wrap the RxScala Observable inside the implicit class, not the RxJava Observable.

**Comment by dhoepelman** [comment]
I personally find `compose` much clearer, as a workaround, it's not difficult to add compose yourself as an extension method:

```
implicit class ObservableCompose[T](val obs: Observable[T]) extends AnyVal {
  def compose[U](transformer: Observable[T] => Observable[U]): Observable[U] = f(obs)
}
```

**Comment by dhoepelman** [comment]
Due to project EOL status, no new operators will be added.
