### ISSUE TITLE
.debounce can't take durationSelector?

### ISSUE THREAD

**Issue by spacetimedecor** [ReactiveX/RxScala#242]
Hello!

I've seen that RxJS's .debounce can take a durationSelector, which I believe makes the operator's timespan variable. This is what I'd like to achieve in RxScala/RxJava but it doesn't seem to be possible in these version's of .debounce. 

I wonder if it is infact possible? If not, it there possibly a workaround? 

Cheers

**Comment by dhoepelman** [comment]
Due to project EOL status, no changes to operators will be made
