### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by dhoepelman** [ReactiveX/RxScala#244]
Hello,

Interest in RxScala seems to have waned over time, in favor of other streaming frameworks in the Scala ecosystem. This is visible in multiple ways

 * Many RxJava 1.2+ features were never ported to RxScala, or [too late to be worth it](https://github.com/ReactiveX/RxScala/pull/239).
  * RxJava 1 is EOL, and an [RxJava 2 equivalent for RxScala never materialized](https://github.com/ReactiveX/RxScala/issues/227)
  * There is no Scala 2.13 RxScala release 5 months after 2.13 was released, [although a PR has been merged to master](https://github.com/ReactiveX/RxScala/pull/243)
  * The last release was [nearly 3 years ago](https://mvnrepository.com/artifact/io.reactivex/rxscala_2.12/0.26.5)

While this is sad for people who like using the Rx model in scala, there are lot of good Scala alternatives in [akka streams](https://doc.akka.io/docs/akka/current/stream/index.html), [monix](https://monix.io/), [cats-effect](https://typelevel.org/cats-effect/), [fs2](https://github.com/functional-streams-for-scala/fs2) and [ZIO](https://zio.dev/) (apologies in advance if I missed one). Scala community interest has drifted to those over time. [RxJava 3](https://github.com/ReactiveX/RxJava) or [Reactor](https://projectreactor.io/) are also alternaties for developers who are willing to use RxScala-like libraries that are less Scala idiomatic

This leaves RxScala 1. My proposal is to put the project in an official End-of-life (EOL) or maintenance only state. This creates clarity about the state of the project and makes sure effort of both potential users and the community is not wasted. It says nothing about a potential RxScala 3 if someone is interested in starting that.

I am willing to perform some work here, which would entail:

* Updating the README to clarify the project status and alternatives/migration paths
* Performing releases, Scala version updates and minor bugfixes

I cannot do the second because I have no release rights, so either I would need get those or releases would need to be done when needed by someone else

@zsxwing @samuelgruetter @xuwei-k what do you think?

**Comment by samuelgruetter** [comment]
Sounds good to me @dhoepelman, thanks for taking care of this!
Looks like I only have write access, but not admin access to grant you write/releases access, but maybe @zsxwing or @akarnokd has?

**Comment by akarnokd** [comment]
Unfortunately I don't have admin access either.

**Comment by samuelgruetter** [comment]
Ok next try: @benjchristensen could you please grant write access for the RxScala repo to @dhoepelman?

**Comment by benlesh** [comment]
Hey I'm an admin on ReactiveX, I'm going to give @akarnokd admin here, and I'll add @dhoepelman as having write permissions. Have a great day and thanks for taking care of this!

**Comment by benlesh** [comment]
Okay, all is done! @dhoepelman, you should have an invite in your email.

**Comment by dhoepelman** [comment]
Thanks @benlesh and @samuelgruetter!
