### ISSUE TITLE
The next version should be 0.21.2 or 0.22.1?

### ISSUE THREAD

**Issue by zsxwing** [ReactiveX/RxScala#28]
I'm trying to merge https://github.com/ReactiveX/RxJava/pull/1701 into RxScala. Therefore, I have to upgrade RxJava from 1.0.0-RC3 to 1.0.0-RC4.

However, RxJava 1.0.0-RC4 contains a breaking change: [Pull 1716 Remove Observable.Parallel](https://github.com/ReactiveX/RxJava/pull/1716). So if we upgrade to 1.0.0-RC4, we also need to make a breaking change in RxScala: removing `parallel`.

So there are two options here:
- Don't merge https://github.com/ReactiveX/RxJava/pull/1701 until we move to 0.22.1
- Merge https://github.com/ReactiveX/RxJava/pull/1701, remove `parallel` and set the next version to 0.22.1

**Comment by jbripley** [comment]
0.21.1 is a bit unfortunately named, since we're  still dependent on RxJava 1.0.0-RCx. 0.21.0-RC1 would have been better in that regard.

I suggest we name the next release with your changes 0.22.0-RC1. I want to upgrade us to RxJava 1.0.0-RC5 whenever that's released, so I can mirror the signature changes to retryWhen/repeatWhen, which will also break the public API. I can then make that 0.22.0-RC2.

We can then keep the 0.22.0-RC releases going until RxJava is 1.0 and then do 0.22.0.

**Comment by samuelgruetter** [comment]
Let's move forward and do these breaking changes, and name the next release `0.22.something`.
I'm not yet quite sure whether `something` should contain `RC` or not. @jbripley do you mean a non-RC RxScala release should not depend on an RC RxJava release?

**Comment by jbripley** [comment]
Yes, it feels a bit weird having a "stable" RxScala release being dependent on a RxJava release candidate.

I don't see the harm doing a couple of RxScala RC releases while we wait for RxJava to get to 1.0.

**Comment by zsxwing** [comment]
Is there any reason that RxScala should release something before RxJava 1.0? Maybe we can just wait for it.

**Comment by headinthebox** [comment]
We should just wait.

**Comment by jbripley** [comment]
That's true, we don't need to do any RxScala RC's, I was getting ahead of myself.

So we just treat the `0.x` branch as the upcoming 0.22.0 release from now until RxJava `1.0` then?

**Comment by samuelgruetter** [comment]
> So we just treat the 0.x branch as the upcoming 0.22.0 release from now until RxJava 1.0 then?

I'd say so.

And if someone needs an RxScala release before RxJava 1.0 is out, we can still release a 0.22.0-RC1.

**Comment by zsxwing** [comment]
Closed since we all agree on waiting for RxJava 1.0
