### ISSUE TITLE
how to access rxjava-contrib?

### ISSUE THREAD

**Issue by fommil** [ReactiveX/RxScala#31]
I'm trying to migrate from

``` scala
  "com.netflix.rxjava" % "rxjava-scala" % "0.17.0-RC2" intransitive(),
  "com.netflix.rxjava" % "rxjava-core" % "0.17.0-RC2" intransitive(),
  "com.netflix.rxjava" % "rxjava-string" % "0.17.0-RC2" intransitive(),
```

to whatever the latest is, but it seems that by moving to `"io.reactivex" %% "rxscala" % "0.21.1"` I lose all the `-contrib` content such as `StringObservable`.

It looks like all the contrib material has been axed from 1.0.0... how am I supposed to use it? Is there a build of rxscala that depends on the 0.20 branch? It seems to be making releases after the 1.0.0 line. I'm very confused by the version system in place here.

**Comment by zsxwing** [comment]
`contrib/rxjava-string` was split into https://github.com/ReactiveX/RxJavaString
You can use the latest release: https://github.com/ReactiveX/RxJavaString/releases/tag/v0.21.0

**Comment by fommil** [comment]
it hasn't been published yet https://github.com/ReactiveX/RxJavaString/issues/3
