### ISSUE TITLE
Recursive scheduling

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxScala#33]
Should we add support for recursive scheduling in RxScala? The signature `def schedule(action: => Unit): Subscription` is very elegant for single shot work, but recursive scheduling (https://github.com/Netflix/RxJava/wiki/Scheduler) is less nice.

---

Originally filed by @headinthebox at https://github.com/ReactiveX/RxJava/issues/1348

**Comment by gkhom** [comment]
Perhaps I'm missing something but this was already added in [#1537](https://github.com/ReactiveX/RxJava/pull/1537)

**Comment by benjchristensen** [comment]
If it's done please confirm and close. I just opened this because https://github.com/ReactiveX/RxJava/issues/1348 was still open while I was reviewing RxJava issues.

**Comment by gkhom** [comment]
The RxScala `scheduleRec(action: => Unit): Subscription` method is [here](https://github.com/ReactiveX/RxScala/blob/0.x/src/main/scala/rx/lang/scala/Scheduler.scala#L101).
But I don't have the rights to close this issue :-)

**Comment by headinthebox** [comment]
I do ;-)
