### ISSUE TITLE
RxScala 1.0

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxScala#34]
What needs to happen for RxScala to hit 1.0 and be considered a final supported API?

**Comment by samuelgruetter** [comment]
I've just added some issues that should imho be addressed before 1.0: #35, #36, #37, #38, #39, #40. And the other open issues should all be addressed as well, of course.

**Comment by headinthebox** [comment]
Those issues look good. I still have a few bugs filed against me as well.

**Comment by thomasnield** [comment]
Considering RxJava 2.0 is now out, what is the status of doing a 1.0 release (much less a 2.0) for RxScala?

**Comment by samuelgruetter** [comment]
RxScala has now been out for more than 3 years, with some continuous improvements, so imho we could make a 1.0 release soon.

Regarding the status of the open issues:

There are two topics where I hoped that there would be a good solution, but none was found, so I'm ready to "give up" on these now:

* Avoid having two overloads for all operators which have a default scheduler: Solutions based on implicits (https://github.com/ReactiveX/RxScala/issues/16) and solutions based on default arguments (https://github.com/ReactiveX/RxScala/issues/40, https://github.com/ReactiveX/RxScala/pull/43) were attempted, but none succeeded.
* Some overloading/inference problems with subscribe (https://github.com/ReactiveX/RxScala/issues/78). The general problem is that overloading is "considered bad" in Scala, so there's little hope that scalac will improve on this, and no workarounds were found.

And I think these should be addressed before a 1.0 release:

* collect/scan/foldLeft signatures (https://github.com/ReactiveX/RxScala/issues/63)
* Remove `create[T](f: Observer[T] => Subscription)` (https://github.com/ReactiveX/RxScala/issues/206)
* replace `=> Unit` by `() => Unit` (https://github.com/ReactiveX/RxScala/issues/225)
* remove all deprecated methods

And optionally:

* Moving the examples from RxScalaDemo to the examples sub-project (and possibly integrating them into the website from there) (https://github.com/ReactiveX/RxScala/issues/37)

Postponing to a future RxScala based on RxJava2:

* Common RxScala API allowing to swap RxJava by RxJs (https://github.com/ReactiveX/RxScala/issues/161)
* New kinds of Observables such as Completable and Single (https://github.com/ReactiveX/RxScala/issues/186, https://github.com/ReactiveX/RxScala/issues/187)

What do others think of this "roadmap"? Comments welcome :wink:

**Comment by thomasnield** [comment]
Sounds good. I ask because I'm about to release a "Reactive Python for Data Science" video and webcast series with OReilly Media. They've been receptive to ReactiveX being taught for data science, so I mentioned an idea to teach a counterpart for Scala. They reacted positively to that,  so I am going to start some R&D work to see what value RxScala has for data analysis and Spark... and possibly launch more content with OReilly.

But most folks are more comfortable using a technology that is at a 1.0 release, so that might be a contingency.

**Comment by dhoepelman** [comment]
Due to project EOL status, these changes will not be made.
