### ISSUE TITLE
Scaladoc

### ISSUE THREAD

**Issue by samuelgruetter** [ReactiveX/RxScala#35]
The scaladoc needs some attention:
-    Some classes/methods don't have any documentation, eg [Producer](http://reactivex.io/rxscala/scaladoc/index.html#rx.lang.scala.Producer)
-    Some links to other classes don't work, or are displayed in full length, eg "rx.lang.scala.Observer" instead of just "Observer"
-    Running `sbt doc` spits out a lot of warnings.

Some remarks:
-    The goal is not to ensure stupid regularity like, for instance, the requirement that every method has a `@return` -- the [scaladoc guide](http://docs.scala-lang.org/style/scaladoc.html) says it shouldn't be added if it's just the same as the whole documentation. But rather, it should be helpful for someone reading it ;-)
-    Using variables, code duplication in the documentation can be avoided.
-    To avoid duplicate or unnecessary work, this should be the last thing we do before releasing 1.0.

**Comment by dhoepelman** [comment]
Due to project EOL status, this improvement will not be made.
