### ISSUE TITLE
Fail the build if CompletenessTest is not happy

### ISSUE THREAD

**Issue by samuelgruetter** [ReactiveX/RxScala#36]
The [CompletenessTest](https://github.com/ReactiveX/RxScala/blob/0.x/src/test/scala/rx/lang/scala/CompletenessTest.scala) ensures that:
-    all methods of the Java Observable have a corresponding method in the Scala Observable, or a comment on why they don't
-    all Scala methods mentioned in the test actually exist
-    all Java methods mentioned in the test actually exist

If any of these fails, it prints some warnings. However, now that RxScala has its own build, CompletenessTest should fail the build if it isn't happy.

**Comment by jbripley** [comment]
I could take a look at this one.
