### ISSUE TITLE
Move RxScalaDemo & Example Coverage

### ISSUE THREAD

**Issue by samuelgruetter** [ReactiveX/RxScala#37]
It would be nice to move the examples in [RxScalaDemo](https://github.com/ReactiveX/RxScala/blob/0.x/examples/src/test/scala/rx/lang/scala/examples/RxScalaDemo.scala) to the [examples](https://github.com/ReactiveX/RxScala/tree/0.x/examples/src/main/scala) subproject, with one file per operator, so that it's easier to navigate through the examples, and that they can be included in the website.

Additionally, a check that each operator has an example needs to be done. This is not for aesthetic reasons or out of completeness-mania, but because throughout RxScala's history, writing examples revealed many issues with the signatures of the operators (the last being https://github.com/ReactiveX/RxScala/pull/24 which even resulted in a [signature change](https://github.com/ReactiveX/RxJava/pull/1720) in the RxJava core...)

Related to https://github.com/ReactiveX/reactivex.github.io/issues/43.

**Comment by dhoepelman** [comment]
Due to project EOL status, this improvement will not be made.
