### ISSUE TITLE
Observable.collect

### ISSUE THREAD

**Issue by experquisite** [ReactiveX/RxScala#4]
Similar to other Scala collections, it would be very helpful to have a collect(), taking the usual partial function, to simultaneously filter and map.  An example use case is unwrapping one of several case classes with a single partial match and forwarding on the contents, useful for processing one message type out of several flowing on the observable.

**Comment by benjchristensen** [comment]
cc @samuelgruetter @zsxwing

**Comment by zsxwing** [comment]
@experquisite do you mean the `collect` in the scala collection api?

``` Scala
def collect[B, That](pf: PartialFunction[A, B])(implicit bf: CanBuildFrom[List[A], B, That]): That
```

I think it's helpful. Do you think the following API is what you want?

``` Scala
def collect[B](pf: PartialFunction[A, B]): Observable[B]
```

**Comment by zsxwing** [comment]
I'll add it once the build script is set up.

**Comment by experquisite** [comment]
Yes that would be most excellent.  Thanks!

**Comment by headinthebox** [comment]
Cool.

**Comment by samuelgruetter** [comment]
+1

There are actually quite a few methods on Scala collections which are not in RxJava, but would be useful in RxScala. We noticed this a long time ago already, but so far no one checked all Scala collection methods on whether they would be useful in RxJava. Quoting the outdated [TODO list](https://github.com/ReactiveX/RxScala/blob/master/TODO.md):

>  Add methods present in Scala collections library, but not in RxJava, e.g. aggregate à la Scala, collect, tails, ...

**Comment by benjchristensen** [comment]
Go ahead and start working in this code base. This new repo will be for 0.21 and beyond. We can't release anything yet and don't have PR auto building right now, but dev can continue with PRs being tested on local dev machines.

**Comment by zsxwing** [comment]
`collect` is added in https://github.com/ReactiveX/RxJava/pull/1623

**Comment by zsxwing** [comment]
Close as already added in https://github.com/ReactiveX/RxJava/pull/1623
