### ISSUE TITLE
Use default arguments for default schedulers

### ISSUE THREAD

**Issue by samuelgruetter** [ReactiveX/RxScala#40]
Many methods have two versions: One without scheduler, which uses some default scheduler, and one which takes a scheduler provided by the user.

Example:

``` scala
def takeRight(time: Duration): Observable[T]
def takeRight(time: Duration, scheduler: Scheduler): Observable[T]
```

Using Scala's default arguments, these two methods could be replaced by just one:

``` scala
def takeRight(time: Duration, scheduler: Scheduler = ComputationScheduler()): Observable[T]
```

For users, this _should_ not cause any breaking changes.

In addition to making the API much smaller, this also provides much better documentation: Just by looking at the signature, you know what the default scheduler is, whereas now, you have to read the documenation (which might be outdated) or even resort to reading the implementation.

This solution is less powerful than what I proposed in https://github.com/ReactiveX/RxScala/issues/16, but it's much easier to understand, and does not break any existing code. Also, since the [Default Schedulers Plugin](https://github.com/ReactiveX/RxJava/blob/master/rxjava-core/src/main/java/rx/plugins/RxJavaDefaultSchedulers.java) now provides support for custom default schedulers, there no need to solve this using implicits.

**Comment by headinthebox** [comment]
I like default arguments (and I think implicit schedulers are too complicated). 
What is nice about default parameters is that it is crystal clear what the scheduler is.
Lets do it.

**Comment by jbripley** [comment]
I could take a look at this one.

**Comment by benjchristensen** [comment]
That is a very nice Scala feature.

**Comment by zsxwing** [comment]
Sorry that I assigned this one to myself by mistake. I planed to assign to @jbripley. However, looks I can only assign to people in ReactiveX.

**Comment by dhoepelman** [comment]
Due to project EOL status, this improvement will not be made.
