### ISSUE TITLE
Missing onBackpressureBuffer/Drop

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxScala#5]
RxScala is missing the onBackpressure operators. We should get these added here and in RxJava 0.20.x. 

In the meantime code can drop down to the underlying Java Observable using https://github.com/ReactiveX/RxScala/blob/master/src/main/scala/rx/lang/scala/JavaConversions.scala

**Comment by zsxwing** [comment]
@benjchristensen I have already done this one in my repo. Do you think if I need to wait for the new build script?

**Comment by benjchristensen** [comment]
You can go ahead and start working on this code base. We just can't do releases yet. 

Changes like this one should also be submitted to the RxJava 0.20.x branch where I can still do releases on the com.netflix.rxjava groupId with the old build and release system. If you do that I'll release 0.20.1 shortly as I have another bug I need to fix as well.

**Comment by zsxwing** [comment]
`onBackpressureBuffer/Drop` is added in https://github.com/ReactiveX/RxJava/pull/1623

**Comment by headinthebox** [comment]
@zsxwing Trapped inside the tarpit now, will take a look over the weekend.

**Comment by zsxwing** [comment]
Close as already added in https://github.com/ReactiveX/RxJava/pull/1623
