### ISSUE TITLE
Remove Observable.compose

### ISSUE THREAD

**Issue by samuelgruetter** [ReactiveX/RxScala#50]
In RxJava, `compose` was added because it allows us to write

``` java
myObservable.op1.op2.op3.compose(f4).op5
```

instead of 

``` java
f4(myObservable.op1.op2.op3).op5
```

where the order of operations is not easy to read.

In Scala, however, I'd never solve this problem using that pattern, but I'd use extension methods, so that I could write

``` scala
myObservable.op1.op2.op3.op4.op5
```

where `op4` is an extension method which does the same as `f4`.
This is much nicer than `compose`, and I think `compose` will confuse users more than be useful for them, so I'd vote for removing it in RxScala. WDYT?

**Comment by headinthebox** [comment]
+1 for not having it. Extension methods FTW.

**Comment by zsxwing** [comment]
+1

**Comment by jbripley** [comment]
+1

**Comment by zsxwing** [comment]
Done in #51
