### ISSUE TITLE
Implementation of tail

### ISSUE THREAD

**Issue by headinthebox** [ReactiveX/RxScala#59]
Why is `tail` not defined as `skip(1)`?

**Comment by samuelgruetter** [comment]
We try to be as similar to Scala Lists as possible, and there, `tail` is not the same as `drop(1)`:

```
scala> List().tail
java.lang.UnsupportedOperationException: tail of empty list

scala> List().drop(1)
res1: List[Nothing] = List()
```

**Comment by headinthebox** [comment]
Cool, can we have Scala-style `range` then as well ;-)

**Comment by zsxwing** [comment]
Closed. We can continue to discuss `range` in #26.
