### ISSUE TITLE
Which are the correct rxscala builds?

### ISSUE THREAD

**Issue by ScottWeinstein** [ReactiveX/RxScala#60]
1. What the README links to [rxjava-scala](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22rxjava-scala%22)
2. What the README says [rxscala](http://search.maven.org/#search%7Cga%7C1%7Crxscala)

**Comment by zsxwing** [comment]
From 0.21, RxScala changed from `"com.netflix.rxjava" % "rxjava-scala"` to `"io.reactivex" %% "rxscala"`. Sorry that README is out of date. Will update it soon.

Thank you for reporting it.

**Comment by zsxwing** [comment]
Already updated README
