### ISSUE TITLE
Upgrade to RxJava 1.0.0

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxScala#66]
I have committed the upgrade to 1.0 but there are a variety of other changes in flight so don't want to release unless you all say it's okay.

Can we release 0.24?

/cc @samuelgruetter @zsxwing @headinthebox

**Comment by headinthebox** [comment]
I have been/am crazy busy until the end of this week. I'd love to take a look at the recent changes, but I trust  @samuelgruetter @zsxwing to make a go/no go for 0.24.

**Comment by zsxwing** [comment]
Should the next version is 0.23.0?

I propose removing `toMap` and `toMultimap` if we plan to release the next version this week. I plan to refactor them in #67 and need some time for discussion.

**Comment by samuelgruetter** [comment]
I think we can release 0.23.0.

> I propose removing toMap and toMultimap if we plan to release the next version this week. I plan to refactor them in #67 and need some time for discussion.

Why do you want to remove them? That would be annoying for users who want to use them.

**Comment by zsxwing** [comment]
> Why do you want to remove them? That would be annoying for users who want to use them.

I was thinking to avoid to release 0.24.0 after 0.23.0 in several days after fixing #67. However, I agree that it's annoying for users. Considering that, I think we can release 0.23.0 now.

**Comment by zsxwing** [comment]
@benjchristensen which tool is best to generate a PR list for a release?

**Comment by benjchristensen** [comment]
I do it manually every time :-) I look through the commit log since the last time and find all the PR references, copy/paste the title and URLS and then my text editor with bulk multi-line editing to format them.

**Comment by zsxwing** [comment]
> I do it manually every time :-) I look through the commit log since the last time and find all the PR references, copy/paste the title and URLS and then my text editor with bulk multi-line editing to format them.

I thought you might have some cool tool.

I'm OK to release 0.23.0 now. @samuelgruetter your opinion?

**Comment by samuelgruetter** [comment]
Yes, let's go :-)

**Comment by zsxwing** [comment]
@benjchristensen could you help release 0.23.0? The release note is in https://github.com/ReactiveX/RxScala/blob/0.x/CHANGES.md

**Comment by headinthebox** [comment]
Thanks a lot guys; I'll stick with 0.23.0 for the next installment of the Coursera MOOC.

**Comment by benjchristensen** [comment]
Anyone with commit privs can release by tagging 0.23.0. 

You can do it via Github via the 'Draft a New Release' at https://github.com/ReactiveX/RxScala/releases

**Comment by benjchristensen** [comment]
I tagged 0.23.0 and kicked off the build: https://travis-ci.org/ReactiveX/RxScala/builds/43202015#L980

**Comment by benjchristensen** [comment]
It is released.

**Comment by samuelgruetter** [comment]
cool, thanks :)

**Comment by zsxwing** [comment]
Cool. I will try to release by myself next time :)
