### ISSUE TITLE
Lack of height attributes for images in scaladocs displays poorly in IntelliJ/IDEA

### ISSUE THREAD

**Issue by DavidMGross** [ReactiveX/RxScala#69]
"Dennis ‏@dnvriend: Too bad #IntelliJIDEA 14 flattens the pretty rxjava images when showing the documentation.. oh well" (https://twitter.com/dnvriend/status/539311261637685248)

This seems to be because the images in the scaladocs do not have height attributes. If you add that attribute to the image elements this problem may go away.  You can use the RxJava source as a guide for that, as the (mostly) same set of images are there complete with height attributes.

**Comment by dnvriend** [comment]
Correct, I copied one image to my own project and set the attribute height="200" and it works:

```
<img width="640" height="200" src="https://github.com/Netflix/RxJava/wiki/images/rx-operators/create.png">
```
