### ISSUE TITLE
rxscala.github.io vs ReactiveX/RxScala

### ISSUE THREAD

**Issue by benjchristensen** [ReactiveX/RxScala#74]
@samuelgruetter Can we now remove the separate RxScala Github org? It takes precedence on Google searches and I think it will confuse people as it is very incomplete. If we're going to spend time on docs and a website I think it would be better to be done at reactivex.io/RxScala.

/cc @headinthebox

**Comment by headinthebox** [comment]
+1 Especially now that the next installment of the Coursera MOOC is up.

**Comment by samuelgruetter** [comment]
Sure, I'll remove the content from http://rxscala.github.io/ and replace it by forwarders to http://reactivex.io/rxscala/, so that the old links still work, but redirect the users to the new site.
@headinthebox when will the next Coursera MOOC begin?

**Comment by benjchristensen** [comment]
Thanks

**Comment by headinthebox** [comment]
AFAIK early 2015.

**Comment by samuelgruetter** [comment]
I added the forwarders, so if you click now on one of these old links, you'll be redirected to the new site [please let me know if it doesn't work in your browser]:

http://rxscala.github.io/
http://rxscala.github.io/scaladoc/index.html#rx.lang.scala.Observable
http://rxscala.github.io/comparison.html

So the old links will continue to work. Ideally, I'd like to avoid 404 on the old links _and_ delete the github org https://github.com/RxScala, but then its repo with the forwarders would be deleted as well, of course. So we can only have one of the two ;-)
