### ISSUE TITLE
subscribe(println) and default args for subscribe

### ISSUE THREAD

**Issue by samuelgruetter** [ReactiveX/RxScala#78]
If `o` is an `Observable[Int]`, this doesn't work:

``` scala
o.subscribe(println)
```

But these work:

``` scala
o.subscribe(println(_))
List(1, 2).foreach(println)
```

Can we make the first one work? And while we're at it, can we reduce the number of `subscribe` methods by using default arguments?

**Comment by headinthebox** [comment]
Scala's lousy type inference always puzzles me ...

**Comment by zsxwing** [comment]
> o.subscribe(println)

It doesn't work because the following ambiguity:

```
overloaded method value subscribe with alternatives:
[error]   (onNext: Int => Unit)rx.lang.scala.Subscription <and>
[error]   (subscriber: rx.lang.scala.Subscriber[Int])rx.lang.scala.Subscription <and>
[error]   (observer: rx.lang.scala.Observer[Int])rx.lang.scala.Subscription
[error]  cannot be applied to (Unit)
[error]     Observable.just(1).subscribe(println)
```

Actually, `foreach` can work:

``` Scala
Observable.just(1).foreach(println)
```

**Comment by zsxwing** [comment]
From the information `cannot be applied to (Unit)`, I guess `Observable.just(1).subscribe(println)` will be compiled to something like:

```
val x = call println() // Then x is `Unit`
Observable.just(1).subscribe(x) // cannot be applied to (Unit)
```
