### ISSUE TITLE
schedulePeriodically

### ISSUE THREAD

**Issue by headinthebox** [ReactiveX/RxScala#84]
I think we can rename `schedulePeriodically` to `schedule` with no ambiguity.

**Comment by samuelgruetter** [comment]
I don't quite like this change. I prefer `schedulePeriodically` because 
1.    when reading it, it's immediately clear what it does, which might not be the case with just `schedule`
2.    whenever possible, we should use the same names as RxJava

just my 2c

**Comment by zsxwing** [comment]
If renaming `def schedulePeriodically(initialDelay: Duration, period: Duration)(action: => Unit): Subscription` to `def schedule(initialDelay: Duration, period: Duration)(action: => Unit): Subscription`,  these two methods will have the same name:

``` Scala
def schedule(delay: Duration)(action: => Unit): Subscription
def schedulePeriodically(initialDelay: Duration, period: Duration)(action: => Unit): Subscription
```

People may think both of them will schedule periodically without reading docs carefully. So I prefer to use different names for them.
