### ISSUE TITLE
Noob question: troubles converting callback to Observable for vertx

### ISSUE THREAD

**Issue by cocodrino** [ReactiveX/RxScala#96]
Hello, I'm trying convert the vertx's event bus callbacks to observables using AsyncSubject, in my dummy test my code works but when I try it inside vertx it compiles fine but the subscribe method never is called, maybe I'm doing a stupid thing but I'm pretty stuck with it and I cant found the mistake

basically I've this code

``` scala
def cllbToObserver[T: ClassTag,R : ClassTag](f: (T => Unit) => R) = {
   val subj = AsyncSubject[T]()
   f(subj.onNext)
   subj.onCompleted()

   subj

}

//sample

import scala.reflect.ClassTag

//a dummy eventBus for demo
def eventSend(url : String, message : String, cllb : String=>Unit)={
   println("some method here")
   cllb(message+"!!")
}

def cllbToObserver[T: ClassTag,R : ClassTag](f: (T => Unit) => R) = {
   val subj = AsyncSubject[T]()
   f(subj.onNext)
   subj.onCompleted()

   subj

}


val z =cllbToObserver(eventSend("Blah:x","Hi!",_ : String=>Unit))

z
  .map((s)=>s+" <--map")
  .subscribe(
onNext = (s)=>{println("result>> "+s)}   //result>> Hi!!! <--map
)

```

this works fine!!..I've tested it with several callbacks and works good...but when I test it inside vertx seems doesnt works

``` scala

def sendRX[OT, IT: ClassTag](address: String, message: OT) =
            cllbToObserver[Message[IT], org.vertx.scala.core.eventbus.EventBus](eb.send(address, message, _: Message[IT] => Unit))

def cllbToObserver[T: ClassTag, R: ClassTag](f: (T => Unit) => R) = {
        val subj = AsyncSubject[T]()
        f(subj.onNext)
        subj.onCompleted()

        subj

    }




/////////////////////////////////////////////////
this is a more simple approach

       def sendRX2[M, R: ClassTag](address: String, message: M) = {
            val sub = AsyncSubject[Message[R]]()
            eb.send(address, message, sub.onNext)
            sub.onCompleted()
            sub

        }

```

this is the type signture from the send method

``` scala

//from source
  def send[ST, RT](address : scala.Predef.String, message : ST, replyHandler : scala.Function1[org.vertx.scala.core.eventbus.Message[RT], scala.Unit])(implicit evidence$3 : scala.Function1[ST, org.vertx.scala.core.eventbus.MessageData], evidence$4 : scala.Function1[RT, org.vertx.scala.core.eventbus.MessageData]) : org.vertx.scala.core.eventbus.EventBus = { /* compiled code */ }

from doc
def send[T](address: String, message: T)(implicit arg0: (T) ⇒ MessageData): EventBus


```

Can you notice some mistake??..or could be caused for the vertx implementation?..please any advice will be appreciate

**Comment by zsxwing** [comment]
Could you elaborate this method?

``` Scala
def cllbToObserver[T: ClassTag,R : ClassTag](f: (T => Unit) => R) = {
   val subj = AsyncSubject[T]()
   f(subj.onNext)
   subj.onCompleted()

   subj

}
```
- Looks you want to use the return value as an `Observable`, but why you call it `cllbToObserver`?
- Does `f` call `subj.onNext` immediately? If not, you may call `AsyncSubject` like:

``` Scala
subj.onCompleted
subj.onNext(v)
```

Then, onNext will be skipped. From this method `eb.send(address, message, f: Message[IT] => Unit)`, I think it will call `f` asynchronously.

**Comment by cocodrino** [comment]
thanks for the reply @zsxwing 

"Looks you want to use the return value as an Observable, but why you call it cllbToObserver?" 
Yes my mistake, must be cllbToObservable instead

``` scala
subj.onCompleted
subj.onNext(v)
```

what would be v? could you provide me an example?...thanks!!!...

**Comment by zsxwing** [comment]
> what would be v?

`v` could be anything. Here is an example that `cllbToObservable` doesn't work:

```
  import rx.lang.scala.subjects.AsyncSubject
  import scala.concurrent.ExecutionContext.Implicits.global
  import scala.concurrent._

  def cllbToObserver[T: ClassTag, R: ClassTag](f: (T => Unit) => R) = {
    val subj = AsyncSubject[T]()
    f(subj.onNext)
    subj.onCompleted()
    subj
  }

  cllbToObserver[Int, String] {
    f => Future {
      Thread.sleep(2000);
      f(1)
    }
      ""
  }.subscribe(println(_))

  Thread.sleep(5000)
```

I guess `eb.send(address, message, f: Message[IT] => Unit)` will call `f` in other thread just like this example.

**Comment by cocodrino** [comment]
mm..ok..I understand your point

'will call f in other thread just like this example"

I think than is worse, every vertx verticle is single thread running inside an event loop, ideally I'd not create other thread inside a verticle... http://vertx.io/manual.html#concurrency ...

  sorry if I'm bothering you with my noob questions, but please let me know if you've any clue of how solve it, but now  I think than the problem is more related to vertx than to RX...

anyway thanks...

**Comment by zsxwing** [comment]
One thing you may not notice: a `Subject` is also an `Observer`. So you should send events to it in sequence. If you want to send events to a `Subject` in different threads, you usually need to use `SerializedSubject`, such as, `val subject = SerializedSubject(AsyncSubject[T]())`. In addition, you also need to make sure you send events in the order as follow:

```
onNext* (onCompleted|onError)?
```

BTW, I noticed that RxScala had not added the `toSerialized` method yet. Will add it soon.

**Comment by cocodrino** [comment]
yes..basically I did my code following these responses 
https://social.msdn.microsoft.com/Forums/en-US/c537c051-36ab-40c7-a395-73850aaf2717/beginner-using-rx-with-method-that-is-passed-a-callback?forum=rx

with toSerialized would be possible write something like the fromCallback method from the RXJs and than works  with mutithreads??..thanks.
